# Generated by Django 5.0.6 on 2024-06-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="orden",
            new_name="order",
        ),
    ]
